/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/exam/create';
import { Create$Params } from '../fn/exam/create';
import { delete$ } from '../fn/exam/delete';
import { Delete$Params } from '../fn/exam/delete';
import { ExamResponse } from '../models/exam-response';
import { exams } from '../fn/exam/exams';
import { Exams$Params } from '../fn/exam/exams';
import { PageResponseExamResponse } from '../models/page-response-exam-response';
import { update } from '../fn/exam/update';
import { Update$Params } from '../fn/exam/update';

@Injectable({ providedIn: 'root' })
export class ExamService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `exams()` */
  static readonly ExamsPath = '/exams';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `exams()` instead.
   *
   * This method doesn't expect any request body.
   */
  exams$Response(params: Exams$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseExamResponse>> {
    return exams(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `exams$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  exams(params: Exams$Params, context?: HttpContext): Observable<PageResponseExamResponse> {
    return this.exams$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseExamResponse>): PageResponseExamResponse => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/exams';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamResponse>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<ExamResponse> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExamResponse>): ExamResponse => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/exams/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/exams/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<ExamResponse>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<ExamResponse> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<ExamResponse>): ExamResponse => r.body)
    );
  }

}
