/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExamResponse {
  courseId?: string;
  creatorId?: string;
  description?: string;
  duration?: string;
  id?: string;
  title?: string;
}
