/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExamRequest {
  courseId: string;
  description: string;
  duration: string;
  title: string;
}
