/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  age?: string;
  createdAt?: string;
  email?: string;
  gender?: string;
  id?: string;
  isApproved?: boolean;
  isVerified?: boolean;
  name?: string;
  role?: string;
}
