/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseExamResponse } from '../../models/page-response-exam-response';

export interface Exams$Params {
  'course-id': string;
  page?: number;
  size?: number;
}

export function exams(http: HttpClient, rootUrl: string, params: Exams$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseExamResponse>> {
  const rb = new RequestBuilder(rootUrl, exams.PATH, 'get');
  if (params) {
    rb.query('course-id', params['course-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseExamResponse>;
    })
  );
}

exams.PATH = '/exams';
