spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: main
            uri: lb://INSTITUTE-MANAGEMENT
            predicates:
              - Path=/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
