spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: main
            uri: lb://main
            predicates:
              - Path=/**
            filters:
              - name: CircuitBreaker
                args:
                  name: main
                  fallbackUri: forward:/fallback/service-unavailable

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
