/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CourseResponse } from '../../models/course-response';

export interface Course$Params {
  'course-id': string;
}

export function course(http: HttpClient, rootUrl: string, params: Course$Params, context?: HttpContext): Observable<StrictHttpResponse<CourseResponse>> {
  const rb = new RequestBuilder(rootUrl, course.PATH, 'get');
  if (params) {
    rb.path('course-id', params['course-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CourseResponse>;
    })
  );
}

course.PATH = '/courses/{course-id}';
