/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ExamService } from './services/exam.service';
export { UserService } from './services/user.service';
export { CourseService } from './services/course.service';
export { AuthenticationService } from './services/authentication.service';
